---
- name: Ensure backup folder exists.
  file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0775

- name: Copy backup script to server.
  template:
    src: backup.sh.j2
    dest: "{{ backup_path }}/backup.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0744


- name: Configure backup cron job.
  cron:
    name: "Backup cron job"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    user: "{{ backup_user }}"
    job: "{{ backup_path }}/backup.sh"
    state: "{{ backup_cron_job_state }}"


- include: databases.yml
  when: backup_mysql
